### ISSUE TITLE
Failing tests on Node.js with IndexedDBShim

### ISSUE THREAD

**Issue by aral** [dfahlander/Dexie.js#709]
This is a preliminary list of the Dexie test suite failing tests on Node.js with IndexedDBShim when run with the new node test runner. Some of these errors may be due to the environment created by the test runner itself and possibly some by non-isomorphic code in the tests themselves. I’m gathering these in one place to give an overview of the current state of Dexie on Node.js with IndexedDBShim. It might be best to either use this issue to track and update the state or to pull out specific tests into their own issues.

@dfahlander has written up [an analysis and a summary](https://github.com/dfahlander/Dexie.js/issues/701#issuecomment-392756378) of the current state of Node.js support via IndexedDBShim based on a preliminary run of these tests.

## tests-table.js

* [ ] 23 - Karl found first on last 'Faadersköld', expected: "Karl", got: "David", test: where, module: table
* [ ] 24 - David found second on last 'Fahlander', expected: "David", got: "Karl", test: where, module: table
* [ ] 25 - Finding items from array members. Expect to fail on IE10/IE11., expected: 1, got: 2, test: where, module: table
* [ ] 104 - BarC should be second (updated previous ID, expected: "BarC", got: "BarB", test: bulkPut - mixed inbound autoIncrement, module: table
* [ ] 105 - BarB should be third (got new key), expected: "BarB", got: "BarC", test: bulkPut - mixed inbound autoIncrement, module: table
 * [ ] 114 - ReferenceError: notEqual is not defined, expected: true, got: false, test: delete, module: table
* [ ] 115 - ReferenceError: notEqual is not defined, expected: true, got: false, test: delete(using transaction), module: table
* [ ] 123 - Test timed out, expected: undefined, got: null, test: failNotIncludedStoreTrans, module: table

## tests-collection.js

* [ ] 10 - First is Karl, expected: "Karl", got: "David", test: toArray, module: collection
* [ ] 11 - Second is David, expected: "David", got: "Karl", test: toArray, module: collection
* [ ] 13 - First is Karl, expected: "Karl", got: "David", test: limit, module: collection
* [ ] 40 - Got Karl, expected: "Karl", got: "David", test: first, module: collection
* [ ] 68 - TypeError: str.replace is not a function, expected: true, got: false, test: keys, module: collection
* [ ] 70 - TypeError: str.replace is not a function, expected: true, got: false, test: uniqueKeys, module: collection
* [ ] 72 - TypeError: str.replace is not a function, expected: true, got: false, test: primaryKeys, module: collection
* [ ] 74 - TypeError: str.replace is not a function, expected: true, got: false, test: primaryKeys2, module: collection
* [ ] 92 - Test timed out, expected: undefined, got: null, test: or-issue#15-test, module: collection
* [ ] Bail out (script timeout) after tests run.

## tests-whereclause.js

* [ ]  227 - Test timed out, expected: undefined, got: null, test: Issue #696 - Query on multiple multi-entry indexes doesn't seem to work, module: WhereClause

## tests-transaction.js

* [ ] 10 - Test timed out, expected: undefined, got: null, test: Table not in transaction 2, module: transaction
* [ ] 12 - Test timed out, expected: undefined, got: null, test: Write into readonly transaction, module: transaction
* [ ] 14 - Test timed out, expected: undefined, got: null, test: Inactive transaction, module: transaction
* Bail out (script timeout) after successfully running/passing test 15

## tests-open.js

* [ ] 18 - Test timed out, expected: undefined, got: null, test: test-if-database-exists, module: open
* [ ] 19 - Test timed out, expected: undefined, got: null, test: test-if-database-exists, module: open
* [ ] 20 - Expected 3 assertions, but 4 were run, expected: undefined, got: null, test: test-if-database-exists, module: open
* [ ] 21 - Test timed out, expected: undefined, got: null, test: open database without specifying version or schema, module: open

## tests-yield.js

All pass.

## tests-asyncawait.js

* [ ] 12 - Error: TransactionInactiveError: A request was placed against a transaction which is currently not active, or which is finished, expected: true, got: false, test: Should be able to use native async await, module: asyncawait

## tests-exception-handling.js

* [ ] 1 - unhandledrejection should have been signaled, expected: 1, got: 0, test: Uncaught promise should signal 'unhandledrejection', module: exception-handling
* [ ] 6 - Test timed out, expected: undefined, got: null, test: transaction should abort on collection error, module: exception-handling
* [ ] 7 - Test timed out, expected: undefined, got: null, test: eventError-transaction-catch, module: exception-handling (looks like the test is oddly run twice in the output)

## tests-upgrading.js

* [ ] 25 - Error: ReferenceError: deepEqual is not defined, expected: true, got: false, test: upgrade, module: upgrading

## tests-misc.js

* [ ] 18 - Test timed out, expected: undefined, got: null, test: #360 DB unresponsive after multiple Table.update() or Collection.modify(), module: misc – _is this due to the test runner timeout or a genuine failure?_

## tests-promise.js

All the errors stem from the same use of non-isomorphic code in the test (window.addEventListener). This will be a quick fix.

* [ ] 12 - Died on test #1     at asyncTest (/Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:1305:8): window.addEventListener is not a function, expected: undefined, got: null, test: onunhandledrejection should propagate once, module: promise – __non-isomorphic test code__
* [ ] 13 - Died on test #1     at asyncTest (/Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:1305:8): window.addEventListener is not a function, expected: undefined, got: null, test: onunhandledrejection should not propagate if catched after finally, module: promise  – __non-isomorphic test code__
* [ ] 28 - Died on test #1     at asyncTest (/Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:1305:8): window.addEventListener is not a function, expected: undefined, got: null, test: unhandledrejection, module: promise – __non-isomorphic test code__
* [ ] 29 - Died on test #1     at asyncTest (/Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:1305:8): window.addEventListener is not a function, expected: undefined, got: null, test: unhandledrejection2, module: promise – __non-isomorphic test code__
* [ ] 30 - Died on test #1     at asyncTest (/Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:1305:8): window.addEventListener is not a function, expected: undefined, got: null, test: unhandledrejection3, module: promise – __non-isomorphic test code__

## tests-extendability.js

All pass.

## tests-crud-hooks.js

All pass.

## tests-blobs.js

Blob and FileReader are not supported on Node.js. The test runner was using polyfills in an attempt at isomorphism. @dfahlander suggests the following: “Use UInt8Array instead of Blob to support both node and browser.” (We should prepare an example of how this would work in a universal JS app.)

* [ ] 1 - Error: cannot read as File: {"type":"application/octet-binary","size":4} … expected: true, got: false, test: Test blobs, module: blobs (FileReader.js:266:15 – FileReader.self.readAsArrayBuffer)
* [ ] 3 - Error: cannot read as File: {"type":"application/octet-binary","size":4} … expected: true, got: false, test: Test blob with creating hook applied, module: blobs (FileReader.js:266:15 – FileReader.self.readAsArrayBuffer)

## tests-binarykeys.js

All pass.

(Results on all tests under Node.js are “This browser does not support IndexedDB 2.0”.)

**Comment by dfahlander** [comment]
@aral, I've forked IndexedDBShim and did `npm link` between dexie and the shim. Added you as collaborator so feel free to push fixes to it if you want. Will create a living PR to the upstream as well.

Another way of running the shim is to insert the following lines into the HEAD section of dexie/test/run-unit-tests.html:

```html
  <script src="../node_modules/babel-polyfill/dist/polyfill.min.js"></script>
  <script src="../node_modules/indexeddbshim/dist/indexeddbshim.js"></script>
  <script>
    shimIndexedDB.__useShim();
  </script>
```
Seems to show the same issues as your node tests did, but not all of them.

**Comment by aral** [comment]
@dfahlander Thanks, David. Regarding how we manage IndexedDBShim in Dexie for user space: would you rather that we:

1.  Added it to dependencies so that it would work out of the box. This would probably be the best option if the library is going to embrace its universal nature going forward. My only concern with this is the size of IndexedDBShim, which currently weights in at ~190MB. I was able to shave ~146MB off of that by removing the Unicode.10.0.0 package and instead inlining the 2KB regular expression that was being used from it but that hasn’t made it to master yet.

2. Remove it from package.json for the time being, document the npm link process and keep it as a development feature until it is ready for prime time (when we have a fully-passing test suite for Node).

3. (I’m assuming not, since it’s the worst of three options) keep it in dev-dependencies. This has no advantages but was a quick and simple way for me to work while getting the test suite running in Node.

Let me know and either I’ll be happy to push that change to https://github.com/dfahlander/Dexie.js/pull/707 or please feel free to do so yourself :)

**Comment by dfahlander** [comment]
I think IndexedDBShim fits well as a dev dependency in case we use it in the test suite (as you did in your PR). Based on that, anyone wishing to fix bugs in the shim, could use npm link to replace node_modules/IndexedDBShim with a symbolic link to their local IndexedDBShim code. I hope the time to do npm install won't suffer too much when adding it as a dependency. If so, we could add it as an optional dependency and let the specific tests that use it make sure it's installed.

**Comment by aral** [comment]
@dfahlander Right, makes sense. If we do add it as a dev dependency, however, we should document that Dexie will not run out of the box on Node.js and that you must add IndexedDBShim separately
to your package.json on Node.js.

The time to install shouldn't be a huge issue once Uncode.10.0.0 is added as a dev dependency in IndexedDBShim – that what takes up an overwhelming majority of the space.

**Comment by dfahlander** [comment]
After my recent updated push to IndexedDBShim, I could check 104 and 105 as well:

* 104 - BarC should be second (updated previous ID, expected: "BarC", got: "BarB", test: bulkPut - mixed inbound autoIncrement, module: table
* 105 - BarB should be third (got new key), expected: "BarB", got: "BarC", test: bulkPut - mixed inbound autoIncrement, module: table

It seems the ordering part is solved if my PR goes into IndexedDBShim master.
